#!/usr/bin/env bash
#
bold=$(tput bold)
normal=$(tput sgr0)
me=$(basename "$0")
doi=""
b=""
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "${bold}$me - generate bibtex record for specified doi${normal}"
      echo " "
      echo "${bold}usage:${normal} $me DOI"
      echo " "
      echo "options:"
      echo "-h, --help                show brief help"
      echo "-x XXX[,YYY]              remove unneeded items according to specified key(s)"
      exit 0
      ;;
    -x)
      shift
      if test $# -gt 0; then
        b="$1"
        shift
      fi
      ;;
    *)
      if test $# -gt 0; then
        doi="$1"
        shift
      fi
      ;;
  esac
done

if test -z "$doi" ; then
  echo "DOI is mandaroty but not specified!"
  exit 1
fi

function _t1 {
  oo="$1"
  oo_=$(echo "$oo" | grep -oP '(title\s*=\s*{)\K[^\{\}]*(?=\})' | cut -d ' ' -f1-3)
  arr_=('A' 'AN' 'THE' 'ON' 'DO' 'CAN' 'IS' 'ARE' 'AM' 'WILL' 'THERE' 'SOME')
  o0=$(echo "$oo_" | cut -d ' ' -f1)
  o1=$(echo "$oo_" | cut -d ' ' -f2)
  o2=$(echo "$oo_" | cut -d ' ' -f3)
  if [[ $(echo "${arr_[@]}" | grep -w "${o0^^}") ]] ; then
    if [[ $(echo "${arr_[@]}" | grep -w "${o1^^}") ]] ; then
      echo "${o2,,}"
    else
      echo "${o1,,}"
    fi
  else
    echo "${o0,,}"
  fi
}

function _pure_t1 {
  oo="$1"
  oo=$(echo "${oo}" | sed 's/[{}`:]//g')
  dd=$(echo "${oo}" | grep -o '[\-‐]*')
  if test -n "$dd" ; then
    echo  "${oo}" | grep -oP ".*(?=${dd})"
  else
    echo "${oo}"
  fi
}

doi=$(echo "$doi" | sed 's/https\?:\/\/doi.org\///')
o=$(curl -sLH "Accept: application/x-bibtex" https://doi.org/"$doi")
tt=$(_t1 "${o}")
tt=$(_pure_t1 "$tt")
o=$(echo $o | sed -E 's/(\w*)_[0-9]*([0-9]{2}),/\L\1\2'"${tt}"',/' | sed 's/month=\w*,\? \?//g' | sed 's/DOI=/doi=/' | sed 's/\(pages\s\?=\s\?{\s\?[0-9]\+\s\?\)[–-]\(\s\?[0-9]\+\)/\1--\2/')
if test -n "$b"; then
  for i in $(echo "$b" | tr "," " "); do
    o=$(echo "$o" | sed 's/'"$i"'={[^\{\}]*},\? \?//gI')
  done
fi

echo "$o" | sed 's/\s*\(\w\+\)=\({[^\{\}]*}\)/\n  \1 = \2/g' | sed 's/},\? \?}/}\n}\n/'
