#!/usr/bin/env bash
#
bold=$(tput bold)
normal=$(tput sgr0)
me=$(basename "$0")
doi=""
b=""
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "${bold}$me - generate bibtex record for specified doi${normal}"
      echo " "
      echo "${bold}usage:${normal} $me DOI"
      echo " "
      echo "options:"
      echo "-h, --help                show brief help"
      exit 0
      ;;
    -x)
      shift
      if test $# -gt 0; then
        b="$1"
        shift
      fi
      ;;
    *)
      if test $# -gt 0; then
        doi="$1"
        shift
      fi
      ;;
  esac
done

if test -z "$doi" ; then
  echo "DOI is mandaroty but not specified!"
  exit 1
fi
doi=$(echo "$doi" | sed 's/https\?:\/\/doi.org\///')
o=$(curl -sLH "Accept: application/x-bibtex" https://doi.org/"$doi")
o=$(echo $o | sed -E 's/(\w*)_[0-9]*([0-9]{2}),/\L\1\2,/' | sed 's/month=\w*,\? \?//g' | sed 's/DOI=/doi=/' | sed 's/\(pages\s\?=\s\?{\s\?[0-9]\+\s\?\)[–-]\(\s\?[0-9]\+\)/\1--\2/')
if test -n "$b"; then
  for i in $(echo "$b" | tr "," " "); do
    o=$(echo "$o" | sed 's/'"$i"'={[^\{\}]*},\? \?//gI')
  done
fi

echo "$o" | sed 's/\s*\(\w\+\)=\({[^\{\}]*}\)/\n  \1 = \2/g' | sed 's/},\? \?}/}\n}\n/'
