#!/bin/bash
#
bold=$(tput bold)
normal=$(tput sgr0)
me=$(basename "$0")
tag='Model'
q_=''
pwd_=$(pwd)
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "${bold}$me - check photos under a directory if is produced by MODEL${normal}"
      echo " "
      echo "${bold}usage:${normal} $me [options] MODEL [NDIR [DIRECTORY]]"
      echo " "
      echo "options:"
      echo "-h, --help                show brief help"
      echo "-g, --tag                 specify TAG instead of 'Model'"
      echo "-q                        query only; otherwise move to NDIR (default same as TAG; make it if not exist) under DIRECTORY (default CURRENT)"
      exit 0
      ;;
    -g|--tag)
      shift
      if test $# -gt 0; then
        tag=$1
        shift
      fi
      ;;
    --tag*)
      tag=$(echo $1 | sed -e 's/^[^=]*=//g')
      shift
      ;;
    -q)
      q_='-q'
      shift
      ;;
    *)
      if [ ${a1+1} ]; then
        a2=$1
      elif [ ${a0+1} ]; then
        a1=$1
      else
        a0=$1
      fi
      shift
      ;;
    esac
done

if [ "${a0}" ]; then
  a1=${a1:-${a0}}
  if [ -d "${a2}" ]; then
    echo "cd ${a2}"
    cd ${a2}
  elif [ "${a2}" ]; then
    echo "'${a2}' not a directory; EXIT!!!"
    exit 1
  fi
  if [ -z "${q_}" ]; then
    echo "mkdir -p ${a1}"
    mkdir -p ${a1}
  else
    echo "${bold}in query-only mode; NONE changes on disk!!!${normal}"
  fi
  for i in *; do
    if [ -f "$i" ]; then
      if [[ "$(exiftool -${tag} $i)" == *${a0}* ]]; then
        if [ "${q_}" ]; then
          echo "${i} >>>>> YES"
        else
          echo "${i} >>>>> YES; mv ${i} ${a1}/"
          mv ${i} ${a1}/
        fi
      else
        echo "${i} >>>>> no"
      fi
    fi
  done
  if [ "${a2}" ]; then
    if [ "${s_}" -o "${v_}" ]; then
      echo 'finished; exit.'
    fi
    cd ${pwd_}
  fi
else
  echo "MODEL not specified; exit"
  exit 1
fi
