#!/bin/bash
#
me=$(basename "$0")
ext='*'
pwd_=$(pwd)
while test $# -gt 0; do
 case "$1" in
  -h|--help)
   echo "$me - rename"
   echo " "
   echo "$me [options] [DIRECTORY]"
   echo " "
   echo "options:"
   echo "-h, --help                show brief help"
   echo "-x, --ext=EXT             only applied for files with this extention"
   echo "-p, --prefix=PREFIX       PREFIX_XXXX.EXT; default name of targit directory"
   echo "-i, --ini=INI             basement for increament; default 0"
   echo "-v                        verbose mode"
   exit 0
   ;;
  -x|--ext)
   shift
   if test $# -gt 0; then
    ext="$1"
    shift
   fi
   ;;
  --ext*)
   ext=$(echo $1 | sed -e 's/^[^=]*=//g')
   shift
   ;;
  -p|--prefix)
   shift
   if test $# -gt 0; then
    pre="$1"
    shift
   fi
   ;;
  --prefix*)
   pre=$(echo $1 | sed -e 's/^[^=]*=//g')
   shift
   ;;
  -i|--ini)
   shift
   if test $# -gt 0; then
    k="$1"
    shift
   fi
   ;;
  --ini*)
   k=$(echo $1 | sed -e 's/^[^=]*=//g')
   shift
   ;;
  -v)
   v_='-v'
   shift
   ;;
  *)
   wkd="$1"
   shift
   ;;
 esac
done

if [ "${wkd}" ]; then
 cd "${wkd}"
fi

rn4 -e ${ext} ${v_}
k=${k:-0}
pre=${pre:-$(pwd | sed 's/.*\///')}

function do_something_ {
 local IFS=$'\n'
 for i in $(find . -d 1 -type f -name "[^\.\_]*.${ext}" -exec ls -1tr "{}" +;)
 do 
  k=$((k+1))
  kk=`printf "%4.4d" $k`
  ext_=$(echo "$i" | sed 's/.*\.//')
  if [ "${v_}" ]; then
   echo 'mv' "'$i'" "'${pre}_${kk}.${ext_}'" 
  fi
  mv "$i" "${pre}_${kk}.${ext_}"
 done
}

do_something_

if [ "${wkd}" ]; then
 cd ${pwd_}
fi
#echo $k
