#!/bin/bash
#
bold=$(tput bold)
normal=$(tput sgr0)
me=$(basename "$0")
#ext='*'
pwd_=$(pwd)
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "${bold}$me - add .x before extension in filename(s)${normal}"
      echo " "
      echo "${bold}usage:${normal} $me [options] [DIRECTORY]"
      echo " "
      echo "options:"
      echo "-h, --help                show brief help"
      echo "-x, --ext=EXT             only applied for files with this extention"
      echo "-s                        simulation mode (not executed)"
      echo "-v                        verbose mode"
      exit 0
      ;;
    -x|--ext)
      shift
      if test $# -gt 0; then
        ext="$1"
        shift
      fi
      ;;
    --ext*)
      ext=$(echo $1 | sed -e 's/^[^=]*=//g')
      shift
      ;;
    -s)
      s_='-s'
      shift
      ;;
    -v)
      v_='-v'
      shift
      ;;
    *)
      wkd_="$1"
      shift
      ;;
  esac
done

if [ "${wkd_}" ]; then
  if [ -d "${wkd_}" ]; then
    if [ "${v_}" ]; then
      echo 'cd '"${wkd_}"
    fi
    cd "${wkd_}"
  else
    echo "'${wkd_}' not a directory; EXIT!!!"
    exit 1
  fi
fi

if [ "${s_}" ]; then                                                          
  echo "${bold}in simulation mode; NONE changes on disk!!!${normal}"                  
fi

for i in [^._]*$([[ "${ext}" ]] && echo ".${ext}" || echo ''); do
  if [ -f "$i" ]; then
    ext_=$([[ "$i" = *.* ]] && echo "${i##*.}" || echo '')
    tmp=$i
    while test -f "${tmp}"; do
      if [ "${ext_}" ]; then
        tmp=$(echo "${tmp}" | sed 's/'"\.${ext_}"$'/'"_x.${ext_}"'/')
      else
        tmp="${tmp}_x"
      fi
    done
    if [ "${s_}" -o "${v_}" ]; then
      echo 'mv' "'$i'" "'${tmp}'"
    fi
    if [ -z "${s_}" ]; then
      mv "$i" "${tmp}"
    fi
  fi
done

if [ "${wkd_}" ]; then
  if [ "${s_}" -o "${v_}" ]; then
    echo 'finished; exit.'
  fi
  cd "${pwd_}"
fi
