#!/bin/bash
#
me=$(basename "$0")
#ext='*'
pwd_=$(pwd)
while test $# -gt 0; do
 case "$1" in
  -h|--help)
   echo "$me - add .x before extension in filename(s)"
   echo " "
   echo "$me [options] [DIRECTORY]"
   echo " "
   echo "options:"
   echo "-h, --help                show brief help"
   echo "-x, --ext=EXT             only applied for files with this extention"
   echo "-v                        verbose mode"
   exit 0
   ;;
  -x|--ext)
   shift
   if test $# -gt 0; then
    ext="$1"
    shift
   fi
   ;;
  --ext*)
   ext=$(echo $1 | sed -e 's/^[^=]*=//g')
   shift
   ;;
  -v)
   v_='-v'
   shift
   ;;
  *)
   wkd_="$1"
   shift
   ;;
 esac
done

if [ "${wkd_}" ]; then
 if [ "${v_}" ]; then
  echo 'cd '"${wkd_}" 
 fi
 cd "${wkd_}"
fi

for i in [^._]*$([[ "${ext}" ]] && echo ".${ext}" || echo ''); do
 ext_=$([[ "$i" = *.* ]] && echo "${i##*.}" || echo '')
 tmp=$i
 while test -f "${tmp}"; do
  if [ "${ext_}" ]; then
   tmp=$(echo "${tmp}" | sed 's/'"\.${ext_}"$'/'"_x.${ext_}"'/')
  else
   tmp="${tmp}_x"
  fi
 done
 if [ "${v_}" ]; then
  echo 'mv' "'$i'" "'${tmp}'"
 fi
 mv "$i" "${tmp}"
done

if [ "${wkd_}" ]; then
 if [ "${v_}" ]; then
  echo 'exit' 
 fi
 cd ${pwd_}
fi
