#!/bin/bash
#
me=$(basename "$0")
ext='*'
pwd_=$(pwd)
while test $# -gt 0; do
 case "$1" in
  -h|--help)
   echo "$me - add .x before extension in filename(s)"
   echo " "
   echo "$me [options] [DIRECTORY]"
   echo " "
   echo "options:"
   echo "-h, --help                show brief help"
   echo "-x, --ext=EXT             only applied for files with this extention"
   echo "-v                        verbose mode"
   exit 0
   ;;
  -x|--ext)
   shift
   if test $# -gt 0; then
    ext="$1"
    shift
   fi
   ;;
  --ext*)
   ext=$(echo $1 | sed -e 's/^[^=]*=//g')
   shift
   ;;
  -v)
   v_=1
   shift
   ;;
  *)
   wkd="$1"
   shift
   ;;
 esac
done

if [ "${wkd}" ]; then
 cd "${wkd}"
fi

for i in *.${ext}; do
 ext_=$(echo "$i" | sed 's/.*\.//')
 tmp=$(echo "$i" | sed 's/'"${ext_}"$'/'"x.${ext_}"'/g')
 if [ "${v_}" ]; then
  echo 'mv' "'$i'" "'${tmp}'"
 fi
 mv "$i" "${tmp}"
done

if [ "${wkd}" ]; then
 cd ${pwd_}
fi
#rn2 "$pd" "x$pd"
